# Generated by Django 6.0.2 on 2026-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsession',
            name='verification_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification_photos/'),
        ),
    ]
