# Generated by Django 6.0.2 on 2026-02-23 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_violations', models.IntegerField(default=0)),
                ('total_violation_score', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=100.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_report', to='exams.examsession')),
            ],
            options={
                'verbose_name': 'Integrity Report',
                'verbose_name_plural': 'Integrity Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
