# Generated by Django 6.0.2 on 2026-02-23 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('window_resize', 'Window Resized'), ('fullscreen_exit', 'Exited Fullscreen'), ('copy_paste', 'Copy/Paste Attempt'), ('right_click', 'Right Click Attempt'), ('head_movement', 'Suspicious Head Movement')], max_length=30)),
                ('severity_score', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examsession')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
