# Generated by Django 6.0.2 on 2026-02-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('window_resize', 'Window Resized'), ('fullscreen_exit', 'Exited Fullscreen'), ('copy_paste', 'Copy/Paste Attempt'), ('right_click', 'Right Click Attempt'), ('head_movement', 'Suspicious Head Movement'), ('identity_mismatch', 'Identity Verification Failure')], max_length=30),
        ),
    ]
